image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - "Build"

Docker Image Build:
  stage: "Build"
  variables:
    DOCKER_IMAGE: "shibme/codeinspect-base"
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
    - docker logout
  only:
    - master
